name: discover-packer
run-name: ${{ github.actor }} is learning GitHub Actions
on: [workflow_dispatch]

jobs:
  check-packer:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
      
      - name: Setup HashiCorp Packer
        uses: hashicorp/setup-packer@v2.0.0
        with:
          version: 1.8.7
      
      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Validate Packer file
        run: packer build sample.json