name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
    inputs:
      username:
        type: string
        description: USERNAME - The name of the user dispacthing the workflow

env:
  USERNAME: ${{ github.event.inputs.username }}

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: echo "Hello $USERNAME"
      - run: echo ${{ secret.SUPER_DUPER_SECRETY_SECRET }}