name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
    inputs:
      username:
        type: string
        description: USERNAME - The name of the user dispacthing the workflow

env:
  USERNAME: ${{ github.event.inputs.username }}
  SUPER_DUPER_SECRETY_SECRET: ${{ secrets.SUPER_DUPER_SECRETY_SECRET }}

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
      
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name:
        run: npm install -g bats
      
      - name: Check bats version
        run: bats -v
      
      - name: Say Hi!
        run: echo "Hello $USERNAME"
      
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      
      - name: Use branch name
        run: echo "Run initiated on branch ${{ steps.extract_branch.outputs.branch }}"